version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bettercorp
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=change_this_in_production
    volumes:
      - ./server:/app
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bettercorp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Celery worker for background tasks
  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: celery -A src.worker.celery worker --loglevel=info
    depends_on:
      - api
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bettercorp
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./server:/app
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: